### ISSUE TITLE
data sets from Monash time series respository don't work

### ISSUE THREAD

**Issue by timoschowski** [awslabs/gluon-ts#1590] opened 2021-06-26 12:55 UTC
## Description
I can download and list the datasets from the Monash time series repository, but can't access them.

## To Reproduce
```python
from gluonts.dataset.repository.datasets import get_dataset, dataset_recipes
from gluonts.dataset.util import to_pandas

# the below works
print(f"Available datasets: {list(dataset_recipes.keys())}")

# this is the output
# Available datasets: ['constant', 'exchange_rate', 'solar-energy', 'electricity', 'traffic', 'exchange_rate_nips', 'electricity_nips', 'traffic_nips', 'solar_nips', 'wiki-rolling_nips', 'taxi_30min', 'kaggle_web_traffic_with_missing', 'kaggle_web_traffic_without_missing', 'kaggle_web_traffic_weekly', 'm1_yearly', 'm1_quarterly', 'm1_monthly', 'nn5_daily_with_missing', 'nn5_daily_without_missing', 'nn5_weekly', 'tourism_monthly', 'tourism_quarterly', 'tourism_yearly', 'm3_monthly', 'm3_quarterly', 'm3_yearly', 'm3_other', 'm4_hourly', 'm4_daily', 'm4_weekly', 'm4_monthly', 'm4_quarterly', 'm4_yearly', 'm5']

# this doesn't work
dataset = get_dataset("nn5_daily_without_missing", regenerate=True)
```

## Error message or code output
(Paste the complete error message, including stack trace, or the undesired output that the above snippet produces.)

```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-13-74488d7bc69b> in <module>
----> 1 dataset = get_dataset("nn5_daily_without_missing", regenerate=True)

~/.pyenv/versions/3.6.9/lib/python3.6/site-packages/gluonts/dataset/repository/datasets.py in get_dataset(dataset_name, path, regenerate)
    228         dataset obtained by either downloading or reloading from local file.
    229     """
--> 230     dataset_path = materialize_dataset(dataset_name, path, regenerate)
    231 
    232     return load_datasets(

~/.pyenv/versions/3.6.9/lib/python3.6/site-packages/gluonts/dataset/repository/datasets.py in materialize_dataset(dataset_name, path, regenerate)
    192     if not dataset_path.exists() or regenerate:
    193         logging.info(f"downloading and processing {dataset_name}")
--> 194         dataset_recipe(dataset_path=dataset_path)
    195     else:
    196         logging.info(

~/.pyenv/versions/3.6.9/lib/python3.6/site-packages/gluonts/dataset/repository/_tsf_datasets.py in generate_forecasting_dataset(dataset_path, dataset_name)
    149         # only one file is exptected
    150         reader = TSFReader(temp_path / archive.namelist()[0])
--> 151         meta, data = reader.read()
    152 
    153     prediction_length = int(meta.forecast_horizon)

~/.pyenv/versions/3.6.9/lib/python3.6/site-packages/gluonts/dataset/repository/_tsf_reader.py in read(self)
     74             self.meta.columns[self.target_name] = None
     75 
---> 76             data = self._read_data_section(lines)
     77 
     78             return self.meta, data

~/.pyenv/versions/3.6.9/lib/python3.6/site-packages/gluonts/dataset/repository/_tsf_reader.py in _read_data_section(self, lines)
     92 
     93         lines = glide.imap_unordered(
---> 94             self._read_data, lines, num_workers=cpu_count(), batch_size=8092
     95         )
     96 

~/.pyenv/versions/3.6.9/lib/python3.6/site-packages/gluonts/nursery/glide/__init__.py in imap_unordered(fn, data, num_workers, batch_size)
     57 def imap_unordered(fn, data, num_workers, batch_size=1):
     58     return ParApply(
---> 59         lift(fn), partition(data, num_workers), batch_size=batch_size
     60     )

~/.pyenv/versions/3.6.9/lib/python3.6/functools.py in wrapper(*args, **kw)
    805                             '1 positional argument')
    806 
--> 807         return dispatch(args[0].__class__)(*args, **kw)
    808 
    809     funcname = getattr(func, '__name__', 'singledispatch function')

~/.pyenv/versions/3.6.9/lib/python3.6/site-packages/gluonts/nursery/glide/_partition.py in partition(xs, n)
     30 def partition(xs, n):
     31     raise NotImplementedError(
---> 32         f"Type {type(xs)} has not implemeted `partition`."
     33     )
     34 

NotImplementedError: Type <class 'list'> has not implemeted `partition`.
```

## Environment
- Operating system: Mac OSX
- Python version: 3.6.9
- GluonTS version: main branch installed with pip install git+https://github.com/awslabs/gluon-ts.git
- MXNet version: 1.7.0

(Add as much information about your environment as possible, e.g. dependencies versions.)

**Comment by timoschowski** [comment] 2021-06-26 12:56
@Schmedu is this something that you've seen?

**Comment by Schmedu** [comment] 2021-06-26 13:46
@timoschowski No, I have not seen that before. It seems to be depending in the python 3.6.9 version, newer versions seem to work. I'll look into that.

**Comment by jaheba** [comment] 2021-06-26 14:30
I think the issue is in glide/_partition.py. The single dispatch.register needs the type passed to the decorator directly in Py 3.6.

**Comment by Schmedu** [comment] 2021-06-28 07:38
@lostella fix worked and it's merged. Thanks for reporting @timoschowski

**Closed by Schmedu** 2021-06-28 07:38 UTC
Labels: bug
