### ISSUE TITLE
How to determine parameters of DeepStateEstimator ?

### ISSUE THREAD

**Issue by parimuns** [awslabs/gluon-ts#634] opened 2020-02-13 10:51 UTC
How to determine state space parameters  (noise_std_bounds ,prior_cov_bounds ,innovation_bounds ) for DeepStateEstimator ?

**Comment by lostella** [comment] 2020-02-13 11:49
closing since this is a duplicate of #610, we'll give an answer there

**Closed by lostella** 2020-02-13 11:49 UTC
Labels: duplicate, question
