### ISSUE TITLE
Error create a custom dataset

### ISSUE THREAD

**Issue by StatMixedML** [awslabs/gluon-ts#592] opened 2020-01-31 13:53 UTC
## Description
The following error is thrown (using the git install version) when I create a custom dataset following the tutorial. Seems to be a recent issue, as it as working Wednesday

## To Reproduce
Using the extended forecasting tutorial [see here](https://gluon-ts.mxnet.io/examples/extended_forecasting_tutorial/extended_tutorial.html#1.3-Use-your-time-series-and-features)

## Error Message
---------------------------------------------------------------------------
GluonTSDataError                          Traceback (most recent call last)
<ipython-input-20-04075e625bc9> in <module>
     58                                                              feat_dynamic_real[:, :-custom_ds_metadata['prediction_length']],
     59                                                              feat_static_cat)],
---> 60                       freq=custom_ds_metadata['freq'])

~/miniconda3/envs/gluonts/lib/python3.6/site-packages/gluonts/dataset/common.py in __init__(self, data_iter, freq, one_dim_target)
    247     ) -> None:
    248         process = ProcessDataEntry(freq, one_dim_target)
--> 249         self.list_data = [process(data) for data in data_iter]
    250 
    251     def __iter__(self) -> Iterator[DataEntry]:

~/miniconda3/envs/gluonts/lib/python3.6/site-packages/gluonts/dataset/common.py in <listcomp>(.0)
    247     ) -> None:
    248         process = ProcessDataEntry(freq, one_dim_target)
--> 249         self.list_data = [process(data) for data in data_iter]
    250 
    251     def __iter__(self) -> Iterator[DataEntry]:

~/miniconda3/envs/gluonts/lib/python3.6/site-packages/gluonts/dataset/common.py in __call__(self, data)
    439     def __call__(self, data: DataEntry) -> DataEntry:
    440         for t in self.trans:
--> 441             data = t(data)
    442         return data
    443 

~/miniconda3/envs/gluonts/lib/python3.6/site-packages/gluonts/dataset/common.py in __call__(self, data)
    378             if self.req_ndim != value.ndim:
    379                 raise GluonTSDataError(
--> 380                     f"Array '{self.name}' has bad shape - expected "
    381                     f"{self.req_ndim} dimensions, got {value.ndim}."
    382                 )

GluonTSDataError: Array 'feat_dynamic_real' has bad shape - expected 2 dimensions, got 1.

## Environment
- Operating system: Linux
- Python version: 3
- GluonTS version: gluonts-0.4.3.dev52+g6f0c16a

(Add as much information about your environment as possible, e.g. dependencies versions.)

**Comment by lostella** [comment] 2020-01-31 14:24
Hi @StatMixedML the issue is probably due to the recently merged #574. The notebook you linked was later updated in #577 to reflect this change, see cells 24 and 25 in its [latest version](https://gluon-ts.s3-accelerate.dualstack.amazonaws.com/master/examples/extended_forecasting_tutorial/extended_tutorial.html#1.3-Use-your-time-series-and-features): can you confirm that this works?

Note that we added a link to the master ("latest") version of the documentation in the README, it's better to refer to that if you're working on the master branch, since the "stable" version doesn't get updated until a new release is done.

**Comment by StatMixedML** [comment] 2020-02-03 08:28
Thanks @lostella, the example from the tutorial is working now. 

Only thing is that I get an error when I want to include **FieldName.FEAT_STATIC_CAT**. Instead of having only one feature, I have a hierarchy of static features that I transformed into numeric variable. Hence, each entry is a combination of different hierarchies. An example would be

array([[ 2, 19],
       [ 2,  6],
       [ 2, 10],
       [ 2, 17],
       [ 3, 13],
       [ 6, 18],
       [ 6, 15],
       [ 4,  4],
       [ 4,  6],
       [ 7,  2],
       [ 5, 19],
       [ 5,  4],
       [ 2, 11],
       [ 2,  7],
       [ 2,  4],
       [ 2, 18],
       [ 3, 15],
       [ 7,  1],
       [ 5,  9],
       [ 1, 12]]).

It is an nd.arrary. Before the new maser version, I had no problem using the feature, but now it throws the error

> GluonTSDataError                          Traceback (most recent call last)
<ipython-input-41-95534d0f3ed6> in <module>
      9                                                             feat_dynamic_real_train,
     10                                                             state_industry_train)],
---> 11                       freq = "1M")

~/miniconda3/envs/gluonts/lib/python3.6/site-packages/gluonts/dataset/common.py in __init__(self, data_iter, freq, one_dim_target)
    247     ) -> None:
    248         process = ProcessDataEntry(freq, one_dim_target)
--> 249         self.list_data = [process(data) for data in data_iter]
    250 
    251     def __iter__(self) -> Iterator[DataEntry]:

~/miniconda3/envs/gluonts/lib/python3.6/site-packages/gluonts/dataset/common.py in <listcomp>(.0)
    247     ) -> None:
    248         process = ProcessDataEntry(freq, one_dim_target)
--> 249         self.list_data = [process(data) for data in data_iter]
    250 
    251     def __iter__(self) -> Iterator[DataEntry]:

~/miniconda3/envs/gluonts/lib/python3.6/site-packages/gluonts/dataset/common.py in __call__(self, data)
    439     def __call__(self, data: DataEntry) -> DataEntry:
    440         for t in self.trans:
--> 441             data = t(data)
    442         return data
    443 

~/miniconda3/envs/gluonts/lib/python3.6/site-packages/gluonts/dataset/common.py in __call__(self, data)
    378             if self.req_ndim != value.ndim:
    379                 raise GluonTSDataError(
--> 380                     f"Array '{self.name}' has bad shape - expected "
    381                     f"{self.req_ndim} dimensions, got {value.ndim}."
    382                 )

GluonTSDataError: Array 'feat_static_real' has bad shape - expected 1 dimensions, got 2.

**Closed** 2020-02-03 09:02 UTC
Labels: API change
