### ISSUE TITLE
How to use SeasonalityISSM in the DeepState Model?

### ISSUE THREAD

**Issue by YangZeqin** [awslabs/gluon-ts#1200] opened 2020-12-04 05:48 UTC
I want to use the "m4_hourly" dataset to learn the DeepState Model,but when I set "issm = SeasonalityISSM(7)", I'm having the following problem.

Could you tell me how to solve it?

```python
from gluonts.dataset.repository.datasets import get_dataset
from gluonts.model.deepstate import DeepStateEstimator
from gluonts.model.deepstate.issm import SeasonalityISSM
from gluonts.mx.trainer import Trainer

def load_dataset():
    dataset = get_dataset("m4_hourly",regenerate=False)
    return dataset

def create_estimator(dataset):
    estimator = DeepStateEstimator(
        cardinality=[414],
        freq = dataset.metadata.freq,
        prediction_length = dataset.metadata.prediction_length,
        issm = SeasonalityISSM(7),
        trainer = Trainer(
            ctx = "cpu",
            epochs = 1,
            learning_rate = 1e-3,
            num_batches_per_epoch = 100,
            hybridize=False,
        )
    )

    return estimator

if __name__ == "__main__":
    dataset = load_dataset()
    estimator = create_estimator(dataset)
    predictor = estimator.train(dataset.train)
```

```
Traceback (most recent call last):
  File "D:/python/DeepSSM/deep ISSM.py", line 53, in <module>
    predictor = estimator.train(dataset.train)
  File "D:\python\DeepSSM\gluonts\model\estimator.py", line 254, in train
    training_data, validation_data, num_workers, num_prefetch, **kwargs
  File "D:\python\DeepSSM\gluonts\model\estimator.py", line 233, in train_model
    validation_iter=validation_data_loader,
  File "D:\python\DeepSSM\gluonts\trainer\_base.py", line 308, in __call__
    epoch_loss = loop(epoch_no, train_iter)
  File "D:\python\DeepSSM\gluonts\trainer\_base.py", line 242, in loop
    output = net(*inputs)
  File "C:\Anaconda\envs\time_series\lib\site-packages\mxnet\gluon\block.py", line 540, in __call__
    out = self.forward(*args)
  File "C:\Anaconda\envs\time_series\lib\site-packages\mxnet\gluon\block.py", line 917, in forward
    return self.hybrid_forward(ndarray, x, *args, **params)
  File "D:\python\DeepSSM\gluonts\model\deepstate\_network.py", line 193, in hybrid_forward
    length=self.past_length,
  File "D:\python\DeepSSM\gluonts\model\deepstate\_network.py", line 151, in compute_lds
    ) = self.issm.get_issm_coeff(seasonal_indicators)
  File "D:\python\DeepSSM\gluonts\model\deepstate\issm.py", line 132, in get_issm_coeff
    self.innovation_coeff(seasonal_indicators),
  File "D:\python\DeepSSM\gluonts\model\deepstate\issm.py", line 247, in innovation_coeff
    axis=2
  File "C:\Anaconda\envs\time_series\lib\site-packages\mxnet\ndarray\ndarray.py", line 1695, in squeeze
    return op.squeeze(self, *args, **kwargs)
  File "<string>", line 45, in squeeze
  File "C:\Anaconda\envs\time_series\lib\site-packages\mxnet\_ctypes\ndarray.py", line 92, in _imperative_invoke
    ctypes.byref(out_stypes)))
  File "C:\Anaconda\envs\time_series\lib\site-packages\mxnet\base.py", line 252, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [13:47:56] c:\jenkins\workspace\mxnet-tag\mxnet\src\operator\tensor\./matrix_op-inl.h:2178: Check failed: dshape[axes[i]] == 1 (2 vs. 1) cannot select an axis to squeeze out which has size=2 not equal to one
```

edit (@lostella): fixed snippet to be self-contained

**Comment by lostella** [comment] 2020-12-04 10:27
The issue is that, for hourly data, seasonal features [are constructed](https://github.com/awslabs/gluon-ts/blob/master/src/gluonts/model/deepstate/issm.py#L321) as if there were two seasonality patterns, and very specific ones, which is the default. But since you are specifying the seasonality yourself (and including a single one), then this breaks.

A fix for this would be to have `SeasonalityISSM` class (and not `CompositeISSM`) to produce the features, so that these correspond exactly to the seasonal patterns that one wants (whether the default or a custom ISSM model is used).

@YangZeqin I'm labeling this as a bug, we'll need to fix this, thanks for the report!

cc @rshyamsundar

**Comment by lostella** [comment] 2020-12-22 22:50
@YangZeqin the DeepStateEstimator configuration was improved in #1223, which is now merged in the `master` branch and will be part of the next release.

You can now specify one of the pre-configured seasonal ISSMs, e.g. for [day-of-week seasonality](https://github.com/awslabs/gluon-ts/blob/f8b7ebb44d68f9545f6e30a220841d78fdbb35db/src/gluonts/model/deepstate/issm.py#L265-L266), or define your own custom by specifying number of seasons + feature to be used to identify seasons, e.g.

```python
SeasonalityISSM(num_seasons=31, time_feature=DayOfMonthIndex())
```

for day-of-month seasonality.

**Closed by lostella** 2020-12-22 22:50 UTC
Labels: bug, question
