### ISSUE TITLE
local variable 'lv' referenced before assignment

### ISSUE THREAD

**Issue by dmitra79** [awslabs/gluon-ts#2222] opened 2022-08-18 16:14 UTC
## Description

I was trying to train DeepAREstimator and got this error. It turns out the dataset didn't have any data (got filtered down during preprocesing), but the error is not informative. Looking at the code of [gluonts/mx/trainer/_base.py](https://github.com/awslabs/gluon-ts/blob/v0.9.x/src/gluonts/mx/trainer/_base.py):  `lv` is defined in line 391 inside an iteration, but line 421 is outside so if the iteration doesn't happen (ex. no data) this error gets thrown.

## To Reproduce

```
### empty dataset:
from gluonts.dataset.common import Dataset
from gluonts.dataset.field_names import FieldName
import tensorflow as tf


class TFDataDataset(Dataset):
    def __init__(self):
        """Create a GluonTS Dataset from a tf.data Dataset."""
        self.dataset = []
        self._len = None

    def __iter__(self):
        for example in self.dataset:
            item = None
            yield item

train_ds=TFDataDataset()
test_ds=TFDataDataset()


from gluonts.model.renewal import DeepRenewalProcessEstimator
from gluonts.mx import Trainer

estimator = DeepRenewalProcessEstimator(
    prediction_length=dataset.metadata.prediction_length,
    context_length=100,
    freq=dataset.metadata.freq,
    num_cells=64,
    num_layers=2,    
    trainer=Trainer(
        ctx="cpu",
        epochs=2,
        learning_rate=1e-3,
        num_batches_per_epoch=100
    )
)
predictor = estimator.train(train_ds,test_ds)
```

## Error message or code output

```
  File "/home/datascience/distributed-energy-resource-research/der/experiment/gluon_experiment.py", line 114, in train
    self.predictor = self.estimator.train(train_datasets.train, train_datasets.test)
  File "/home/datascience/conda/derv2/lib/python3.7/site-packages/gluonts/mx/model/estimator.py", line 200, in train
    cache_data=cache_data,
  File "/home/datascience/conda/derv2/lib/python3.7/site-packages/gluonts/mx/model/estimator.py", line 172, in train_model
    validation_iter=validation_data_loader,
  File "/home/datascience/conda/derv2/lib/python3.7/site-packages/gluonts/mx/trainer/_base.py", line 439, in __call__
    num_batches_to_use=self.num_batches_per_epoch,
  File "/home/datascience/conda/derv2/lib/python3.7/site-packages/gluonts/mx/trainer/_base.py", line 421, in loop
    lv,
UnboundLocalError: local variable 'lv' referenced before assignment
```

## Environment
- Operating system: linux
- Python version: 3.7.10
- GluonTS version: 0.9.4
- MXNet version: 1.7.0

**Comment by lostella** [comment] 2022-08-18 16:16
Thanks @dmitra79 makes sense, and I agree this should be caught and reported with a better error message (rather than a coincidental failure)

**Comment by jaheba** [comment] 2022-08-22 13:29
Is this a duplicate of #997? Supposedly there is a fix, but maybe not.

**Comment by lostella** [comment] 2022-08-22 14:04
> Is this a duplicate of #997? Supposedly there is a fix, but maybe not.

Definitely related. We could detect that the data loader produce no batches, and provide a better error message? One clear reason for that is an empty dataset to begin with; another is that its entries are too short, and get filtered out because of the model pre-processing logic; so we could suggest at least checking that.

**Closed as completed** 2022-08-23 08:47 UTC
Labels: bug
