### ISSUE TITLE
MP dataloader ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by rubick1896** [awslabs/gluon-ts#1463] opened 2021-05-14 03:14 UTC
## Description
MP dataloader gives 'ConnectionResetError: [Errno 104] Connection reset by peer'.
The training is fine, this only happens when after the last epoch.

## To Reproduce
MyDataset is just a large iterator that does not hit its end when training is done.
It is doing some dist loading job inside itself. I suppose that should not be a deal-breaker.

```python
    
    multiprocessing.set_start_method("spawn", force=True)

    n_workers = 4
    n_instances = 10 #/ n_workers
    batch_size = 1024
    n_days = np.unique(dline_feature['date']).shape[0] - 20
    #n_epochs = np.ceil(dline_feature.groupby('date')['code'].count().mean() * n_instances / batch_size)
    n_epochs = 10

    train_ds = MyDataset(codes, dts_train, hold_time, dline_feature, dir=dir)

    estimator = DeepAREstimator(freq="1min",
                                num_cells=128,
                                prediction_length=hold_time,
                                context_length=30,
                                use_feat_dynamic_real=True,
                                use_feat_static_cat=True,
                                use_feat_static_real=False,
                                cardinality = [len(codes)],
                                imputation_method=LastValueImputation(),
                                train_sampler=ExpectedNumInstanceSampler(
                                    num_instances=n_instances, min_future=hold_time
                                ),
                                batch_size=batch_size,
                                trainer=Trainer(epochs=n_epochs,
                                                #batch_size=1024,
                                                #learning_rate=2e-2,
                                                weight_decay=1e-6,
                                                learning_rate_decay_factor=0.5,
                                                num_batches_per_epoch=n_days,
                                                ctx=mx.gpu(1)))

    predictor = estimator.train(train_ds, num_workers=n_workers, num_prefetch=n_days)
```

## Error message or code output
(Paste the complete error message, including stack trace, or the undesired output that the above snippet produces.)

```
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 1009/1009 [03:25<00:00,  4.90it/s, epoch=10/10, avg_epoch_loss=-5.34][2021-05-14 02:45:39][gluonts.trainer._base][INFO] Epoch[9] Elapsed time 205.813 seconds
[2021-05-14 02:45:39][gluonts.trainer._base][INFO] Epoch[9] Evaluation metric 'epoch_loss'=-5.343497
[2021-05-14 02:45:39][root.model_averaging][INFO] Computing averaged parameters.
[2021-05-14 02:45:39][root.model_averaging][INFO] Loading averaged parameters.
[2021-05-14 02:45:39][gluonts.trainer._base][INFO] End model training
Process worker_2:
Traceback (most recent call last):
  File "/home/wenrui29/anaconda3/envs/exp3.6/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/wenrui29/anaconda3/envs/exp3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wenrui29/src/gluon-ts/src/gluonts/dataset/loader.py", line 106, in worker_fn
    batch_queue.put(buf.getvalue())
  File "<string>", line 2, in put
  File "/home/wenrui29/anaconda3/envs/exp3.6/lib/python3.6/multiprocessing/managers.py", line 757, in _callmethod
    kind, result = conn.recv()
  File "/home/wenrui29/anaconda3/envs/exp3.6/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/wenrui29/anaconda3/envs/exp3.6/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/wenrui29/anaconda3/envs/exp3.6/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Process worker_1:
Traceback (most recent call last):
  File "/home/wenrui29/anaconda3/envs/exp3.6/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/wenrui29/anaconda3/envs/exp3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
Process worker_0:
  File "/home/wenrui29/src/gluon-ts/src/gluonts/dataset/loader.py", line 100, in worker_fn
    if terminate_event.is_set():
  File "/home/wenrui29/anaconda3/envs/exp3.6/lib/python3.6/multiprocessing/managers.py", line 1026, in is_set
    return self._callmethod('is_set')
File "/home/wenrui29/anaconda3/envs/exp3.6/lib/python3.6/multiprocessing/managers.py", line 757, in _callmethod
    kind, result = conn.recv()
  File "/home/wenrui29/anaconda3/envs/exp3.6/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/wenrui29/anaconda3/envs/exp3.6/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/wenrui29/anaconda3/envs/exp3.6/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Process worker_3:
Traceback (most recent call last):
  File "/home/wenrui29/anaconda3/envs/exp3.6/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/wenrui29/anaconda3/envs/exp3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wenrui29/src/gluon-ts/src/gluonts/dataset/loader.py", line 100, in worker_fn
    if terminate_event.is_set():
  File "/home/wenrui29/anaconda3/envs/exp3.6/lib/python3.6/multiprocessing/managers.py", line 1026, in is_set
    return self._callmethod('is_set')
  File "/home/wenrui29/anaconda3/envs/exp3.6/lib/python3.6/multiprocessing/managers.py", line 757, in _callmethod
    kind, result = conn.recv()
  File "/home/wenrui29/anaconda3/envs/exp3.6/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/wenrui29/anaconda3/envs/exp3.6/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/wenrui29/anaconda3/envs/exp3.6/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
Traceback (most recent call last):
ConnectionResetError: [Errno 104] Connection reset by peer
  File "/home/wenrui29/anaconda3/envs/exp3.6/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/wenrui29/anaconda3/envs/exp3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wenrui29/src/gluon-ts/src/gluonts/dataset/loader.py", line 100, in worker_fn
    if terminate_event.is_set():
  File "/home/wenrui29/anaconda3/envs/exp3.6/lib/python3.6/multiprocessing/managers.py", line 1026, in is_set
```

## Environment
- Operating system: Linux 20.04
- Python version: 3.6.13
- GluonTS version: current master
- MXNet version: 1.7.0

(Add as much information about your environment as possible, e.g. dependencies versions.)

**Comment by lostella** [comment] 2021-05-17 12:49
@rubick1896 if it's not too much work, could you provide a mock implementation for `MyDataset` that resembles the one you used when the error was raised? That would help us reproduce the issue & identify the source

**Comment by lostella** [comment] 2022-07-17 12:31
Closing this since multiprocessing data loader was removed in #2018

**Closed by lostella** 2022-07-17 12:31 UTC
Labels: bug, cannot reproduce
