### ISSUE TITLE
How to finetune a trained network using gluonts

### ISSUE THREAD

**Issue by rubick1896** [awslabs/gluon-ts#979] opened 2020-08-07 08:31 UTC
I have already trained a network on some period of data. As time goes by, new data comes in. I don't want to re-train the whole thing but finetune the network on the newest data. How could I achieve that?

**Comment by jaheba** [comment] 2020-08-10 08:48
This is generally called "incremental learning" and unfortunately, this is currently not possible in gluon-ts.

This is a duplicate of #272.

**Closed by jaheba** 2020-08-10 08:48 UTC
Labels: question
