### ISSUE TITLE
Potential glitches when reading data with ujson

### ISSUE THREAD

**Issue by kashif** [awslabs/gluon-ts#2010] opened 2022-06-09 09:37 UTC
## Description
When I read a dataset via `get_dataset` sometimes I get some strange artifacts in the numerical values of the raw data.

## To Reproduce
(Please provide minimal example of code snippet that reproduces the error. For existing examples, please provide link.)

```python
from gluonts.dataset.repository.datasets import get_dataset

traffic = get_dataset("traffic")
index = 123

test = list(traffic.test)
test[index]["target"][-60:]
```

gives 

```python
array([0.0991, 0.1109, 0.1059, 0.1046, 0.0994, 0.1018, 0.0951, 0.0823,
       0.0817, 0.0736, 0.0662, 0.0647, 0.068 , 0.0697, 0.0472, 0.0298,
       0.0198, 0.0146, 0.0105, 0.0119, 0.0195, 0.0263, 0.0362, 0.0511,
       0.0771, 0.1023, 0.1   , 0.1045, 0.0941, 0.0901, 0.0903, 0.077 ,
       0.0747, 0.0703, 0.0655, 0.0692, 0.0647, 0.0608, 0.0431, 0.0227,
       0.0162, 0.0138, 0.0121, 0.0216, 0.0537, 0.0945, 0.1789, 0.2191,
       0.1024, 0.1265, 0.1061, 0.1025, 0.1024, 0.1023, 0.1074, 0.1159,
       0.1239, 0.1131, 0.0784, 0.0765], dtype=float32)
```

and other times it returns the wrong data (with a missing digit `1` in some places):

```python
test = list(traffic.test)
test[index]["target"][-60:]
```

```python
array([0.0991, 0.109 , 0.1059, 0.1046, 0.0994, 0.108 , 0.0951, 0.0823,
       0.087 , 0.0736, 0.0662, 0.0647, 0.068 , 0.0697, 0.0472, 0.0298,
       0.098 , 0.046 , 0.005 , 0.019 , 0.095 , 0.0263, 0.0362, 0.051 ,
       0.0771, 0.1023, 0.1   , 0.1045, 0.0941, 0.0901, 0.0903, 0.077 ,
       0.0747, 0.0703, 0.0655, 0.0692, 0.0647, 0.0608, 0.0431, 0.0227,
       0.062 , 0.038 , 0.021 , 0.026 , 0.0537, 0.0945, 0.1789, 0.291 ,
       0.1024, 0.1265, 0.1061, 0.1025, 0.1024, 0.1023, 0.1074, 0.159 ,
       0.1239, 0.131 , 0.0784, 0.0765], dtype=float32)
```

## Error message or code output
(Paste the complete error message, including stack trace, or the undesired output that the above snippet produces.)

```
put error or undesired output here
```

## Environment
- Operating system: Ubuntu 20.04
- Python version:  Python 3.8.10
- Numpy version: 1.22.4
- ujson version: 5.3.0
- GluonTS version: 0.9.4 and master
- MXNet version:

(Add as much information about your environment as possible, e.g. dependencies versions.)

**Comment by kashif** [comment] 2022-06-09 09:42
yes I believe so...

**Comment by lostella** [comment] 2022-06-09 10:01
Some thoughts:
- can you reproduce the issue also using the code from `master`?
- can you report what version of `usjons` or `orjson` you are using (if any)?

**Comment by kashif** [comment] 2022-06-09 10:01
@lostella ok I investigated more... the value in the `ProcessTimeSeriesField` before the call to `np.array` is wrong so numpy is not the issue...

**Comment by kashif** [comment] 2022-06-09 10:03
```
 pip list | grep -i json
fastjsonschema                    2.15.3
geojson                           2.5.0
geojsonio                         0.0.3
hjson                             3.0.2
json-tricks                       3.15.5
json5                             0.9.6
jsonschema                        3.2.0
jupyterlab-geojson                3.2.0
osm2geojson                       0.2.0
pysimdjson                        3.2.0
python-json-logger                2.0.2
python-rapidjson                  1.6
rapidjson                         1.0.0
ujson                             5.3.0
```

**Comment by lostella** [comment] 2022-06-09 10:15
@kashif interesting. Could you check if installing `orjson` works? We have some automagic selection for the JSON backend [here](https://github.com/awslabs/gluon-ts/blob/master/src/gluonts/json.py#L130) and `orjson` appears to be the backend with highest priority

**Comment by kashif** [comment] 2022-06-09 10:16
please burn `ujson`!! I have lost a few sleepless nights because of it!!

**Comment by kashif** [comment] 2022-06-09 10:27
yes good idea!

**Comment by jaheba** [comment] 2022-06-14 20:18
Closing this as the issue seem to be caused by `ujson`.

But let's keep an eye on it.

**Closed by jaheba** 2022-06-14 20:18 UTC
Labels: bug, dependency
