### ISSUE TITLE
numpy version issue while installing via pip

### ISSUE THREAD

**Issue by gslin** [awslabs/gluon-ts#54] opened 2019-06-04 10:13 UTC
Ubuntu 16.04.6 LTS, Python 3.7.3 (pyenv).

Using `pip install gluonts` in a clean environment will get version conflict error about.  It will try to install numpy 1.16.4 first:

```
Collecting numpy>=1.14.0 (from gluonts)
  Downloading https://files.pythonhosted.org/packages/fc/d1/45be1144b03b6b1e24f9a924f23f66b4ad030d834ad31fb9e5581bd328af/numpy-1.16.4-cp37-cp37m-manylinux1_x86_64.whl (17.3MB)
```

And later mxnet gives version conflict error:

```
ERROR: mxnet 1.4.1 has requirement numpy<1.15.0,>=1.8.2, but you'll have numpy 1.16.4 which is incompatible.
```

Workaround is to run `pip install mxnet` after `pip install gluonts` to let pip downupgrade numpy:

```
$ pip install mxnet
Requirement already satisfied: mxnet in ./.pyenv/versions/3.7.3/lib/python3.7/site-packages (1.4.1)
Requirement already satisfied: requests>=2.20.0 in ./.pyenv/versions/3.7.3/lib/python3.7/site-packages (from mxnet) (2.22.0)
Collecting numpy<1.15.0,>=1.8.2 (from mxnet)
  Downloading https://files.pythonhosted.org/packages/18/84/49b7f268741119328aeee0802aafb9bc2e164b36fc312daf83af95dae646/numpy-1.14.6-cp37-cp37m-manylinux1_x86_64.whl (13.8MB)
     |████████████████████████████████| 13.8MB 13.5MB/s
Requirement already satisfied: graphviz<0.9.0,>=0.8.1 in ./.pyenv/versions/3.7.3/lib/python3.7/site-packages (from mxnet) (0.8.4)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./.pyenv/versions/3.7.3/lib/python3.7/site-packages (from requests>=2.20.0->mxnet) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in ./.pyenv/versions/3.7.3/lib/python3.7/site-packages (from requests>=2.20.0->mxnet) (2019.3.9)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./.pyenv/versions/3.7.3/lib/python3.7/site-packages (from requests>=2.20.0->mxnet) (1.25.3)
Requirement already satisfied: idna<2.9,>=2.5 in ./.pyenv/versions/3.7.3/lib/python3.7/site-packages (from requests>=2.20.0->mxnet) (2.8)
Installing collected packages: numpy
  Found existing installation: numpy 1.16.4
    Uninstalling numpy-1.16.4:
      Successfully uninstalled numpy-1.16.4
Successfully installed numpy-1.14.6
```

If it's not easy to fix, maybe add some instructions into `README.md`.

**Comment by whyxiang** [comment] 2019-07-26 11:35
> @gslin thanks for reporting this, we've fixed the NumPy version and the problem should not occur on the next tagged release.

@lostella 
hello, gluonts python package was just updated on July 23, seems this numpy version problem is still here.

**Comment by aalexandrov** [comment] 2019-07-26 15:30
Maybe its best to just set an upper bound to the allowed numpy version to `numpy>=1.14.0,<1.15.0` in the [requirements/requirements.txt](https://github.com/awslabs/gluon-ts/blob/master/requirements/requirements.txt#L5) file.

@whyxiang: could you give this a shot on a cloned repo points to the current `master` and applies the suggested fix? The install command should be

```bash
pip install ".[shell]" 
```

**Comment by aalexandrov** [comment] 2019-07-26 15:32
FYI, am I the only one that thinks this is (mildly) unexpected - pip should be able to handle this case automatically by resolving all dependencies upfront and computing the intersection of allowed version ranges for dependencies defined through multiple paths.

**Comment by whyxiang** [comment] 2019-07-27 04:33
@aalexandrov 
Hi Alex, I install glutonts 0.3.0 manually by pip install the .whl file downloaded from pypi.org

I am installing both catboost and gluonts packages, catboost requires numpy >=1.15.0 but gluonts requires numpy ==1.14.*

**Comment by whyxiang** [comment] 2019-07-29 07:48
> Maybe its best to just set an upper bound to the allowed numpy version to `numpy>=1.14.0,<1.15.0` in the [requirements/requirements.txt](https://github.com/awslabs/gluon-ts/blob/master/requirements/requirements.txt#L5) file.
> 
> @whyxiang: could you give this a shot on a cloned repo points to the current `master` and applies the suggested fix? The install command should be
> 
> ```shell
> pip install ".[shell]" 
> ```

hello Alex, I pip install using the gluonts-0.3.0.tar.gz downloaded from pypi.org
After extracting files from .tar.gz, I manually edited requirements/requirements.txt file with numpy>=1.14.*, then just `python setup.py install`

However, the installation cannot be completed. The following warning message shows up, and the installation never moves on
`WARNING:root:Package 'sphinx' not found. You will not be able to build the docs.`

**Comment by aalexandrov** [comment] 2019-07-29 09:20
It seems that the issue is present not just in `gluonts==0.3.0` but also in `mxnet==1.4.1`. 

Both packages require `numpy<1.15.0`, whereas `catboost==0.16` requires `numpy>=1.16.0`, Strictly speaking, this makes `catboost==0.16` incompatible with `gluonts==0.3.0` or `mxnet==1.4.1`.

Maybe it is possible to use `catboost==0.14` or lower?

**Comment by aalexandrov** [comment] 2019-07-29 09:20
> WARNING:root:Package 'sphinx' not found. You will not be able to build the docs.

This is just a warning, it does not mean that the package is not installed.

**Comment by whyxiang** [comment] 2019-07-29 12:24
@aalexandrov 
Hello Alex,

1. Yes, the only solution at this moment is to downgrade catboost with numpy==0.14, and it works. I am just wondering whether it is possible to have gluonts and mxnet compatible with latest version of numpy in the future so there would not be any conflict between the latestest version of mxnet, gluonts and other py packages.

2. the installation cannot be completed,  the warning message is the only thing shows up, no error message. This happens after me manually editing requirement.txt to numpy >=1.14.*.

Anyway, this problem is solved, thanks for help :)

**Closed** 2019-08-23 13:51 UTC
