### ISSUE TITLE
How to deal with sparse time series?

### ISSUE THREAD

**Issue by sixteenyear** [awslabs/gluon-ts#267] opened 2019-08-28 07:02 UTC
#261 
## Description
In the actual application,  some sparse time series will be in a large number of time series. e.g., we're using 1 minutes data, so freq="1min", and there should be 1440 time points in one day.  

If some  time series  only have 300-600 or even 100 time points in one day, and the missing values are padded with 0, can these time series be forecasted precisely by DeepAREstimator or MQCNNEstimator in gluonts?

## Another question
Is there any  better padding methods besdies padding the missing values with 0?

**Comment by lostella** [comment] 2019-08-29 02:28
Duplicate of #261

**Closed by lostella** 2019-08-29 02:28 UTC
Labels: enhancement
