### ISSUE TITLE
ProhetPredictor serialization issue 

### ISSUE THREAD

**Issue by shaida** [awslabs/gluon-ts#1531] opened 2021-06-03 00:41 UTC
## Description
I'm getting a serialization error when initializing a ProphetPredictor. Has anyone else had this issue?
I have prophet `0.7.1` installed on my system. 
## To Reproduce
```
from gluonts.model.prophet import PROPHET_IS_INSTALLED, ProphetPredictor
ProphetPredictor(freq = '1D', prediction_length = 35)

```

## Error message or code output

```
RuntimeErrorTraceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

/usr/local/lib/python3.7/dist-packages/IPython/lib/pretty.py in pretty(self, obj)
    392                         if cls is not object \
    393                                 and callable(cls.__dict__.get('__repr__')):
--> 394                             return _repr_pprint(obj, self, cycle)
    395 
    396             return _default_pprint(obj, self, cycle)

/usr/local/lib/python3.7/dist-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    698     """A pprint that just redirects to the normal repr function."""
    699     # Find newlines and replace them with p.break_()
--> 700     output = repr(obj)
    701     lines = output.splitlines()
    702     with p.group():

~/.local/lib/python3.7/site-packages/gluonts/core/component.py in validated_repr(self)
    308 
    309         def validated_repr(self) -> str:
--> 310             return dump_code(self)
    311 
    312         def validated_getnewargs_ex(self):

~/.local/lib/python3.7/site-packages/gluonts/core/serde/_repr.py in dump_code(o)
    119     """
    120 
--> 121     return as_repr(encode(o))
    122 
    123 

/usr/lib/python3.7/functools.py in wrapper(*args, **kw)
    825                             '1 positional argument')
    826 
--> 827         return dispatch(args[0].__class__)(*args, **kw)
    828 
    829     funcname = getattr(func, '__name__', 'singledispatch function')

~/.local/lib/python3.7/site-packages/gluonts/core/serde/_base.py in encode(v)
    218             # args need to be a list, since we encode tuples explicitly
    219             "args": encode(list(args)),
--> 220             "kwargs": encode(kwargs),
    221         }
    222 

/usr/lib/python3.7/functools.py in wrapper(*args, **kw)
    825                             '1 positional argument')
    826 
--> 827         return dispatch(args[0].__class__)(*args, **kw)
    828 
    829     funcname = getattr(func, '__name__', 'singledispatch function')

~/.local/lib/python3.7/site-packages/gluonts/core/serde/_base.py in encode(v)
    205 
    206     if isinstance(v, dict):
--> 207         return valmap(encode, v)
    208 
    209     if isinstance(v, type):

~/.local/lib/python3.7/site-packages/toolz/dicttoolz.py in valmap(func, d, factory)
     81     """
     82     rv = factory()
---> 83     rv.update(zip(d.keys(), map(func, d.values())))
     84     return rv
     85 

/usr/lib/python3.7/functools.py in wrapper(*args, **kw)
    825                             '1 positional argument')
    826 
--> 827         return dispatch(args[0].__class__)(*args, **kw)
    828 
    829     funcname = getattr(func, '__name__', 'singledispatch function')

~/.local/lib/python3.7/site-packages/gluonts/core/serde/_base.py in encode(v)
    221         }
    222 
--> 223     raise RuntimeError(bad_type_msg.format(fqname_for(v.__class__)))
    224 
    225 

RuntimeError: Cannot serialize type builtins.function. See the documentation of the `encode` and
`validate` functions at

    http://gluon-ts.mxnet.io/api/gluonts/gluonts.html

and the Python documentation of the `__getnewargs_ex__` magic method at

    https://docs.python.org/3/library/pickle.html#object.__getnewargs_ex__

for more information how to make this type serializable.
```

## Environment
- Operating system: mac os
- Python version: Python 2.7.16
- GluonTS version: 0.7.0
- MXNet version: 1.6.0

I would be grateful if you can help me with this issue! thanks

**Comment by lostella** [comment] 2021-06-03 07:18
@shaida there is indeed a serialization issue, but in your case it is showing up simply because the Python interpreter is trying to print out the predictor object. If you instead assign it to a variable, like

```python
p = ProphetPredictor(freq = '1D', prediction_length = 35)
```

then you should be able to use it.

One thing I would advise you, to prevent other issues from showing up, is to use Python 3.6, 3.7 or 3.8.

**Comment by lostella** [comment] 2021-06-03 07:27
[This](https://github.com/awslabs/gluon-ts/blob/master/src/gluonts/model/prophet/_predictor.py#L125) might be the line that's causing it: either making this argument `Optional` and defaulting it to `None` (and instantiate the lambda in the constructor), or defaulting it to a serializable identity function (i.e. not using lambda) should fix it, if this is indeed the root cause.

**Comment by lostella** [comment] 2021-06-03 08:29
Snippet in the OP works fine on `master` with `pydantic==1.7.3` but not with `pydantic==1.8.1`

**Comment by jaheba** [comment] 2021-06-03 08:33
```

**Comment by jaheba** [comment] 2021-06-03 08:42
The `1.8` behaviour is probably what we want still.

As a side-node, `init_model` appears to be never used.

**Closed** 2021-06-03 12:05 UTC
Labels: bug, dependency
