### ISSUE TITLE
Handle large dataset that does not fit in memory

### ISSUE THREAD

**Issue by rubick1896** [awslabs/gluon-ts#996] opened 2020-08-21 10:17 UTC
I have a large dataset that cannot be read into memory as a whole. I implemented a generator based dataset which gives a data entry one at a time. However,  when the data set is passed into the data loader, it calls list(dataset) anyway. What is the solution to this type of problem?

**Comment by lostella** [comment] 2020-08-24 12:34
@rubick1896 what version of GluonTS are you using? Could you point to where `list(dataset)` is called?

**Comment by rubick1896** [comment] 2020-08-25 03:03
@lostella I am using version 0.5.0. I believe it is called in https://gluon-ts.mxnet.io/_modules/gluonts/dataset/parallelized_loader.html#ParallelDataLoader

`
if isinstance(dataset, Sized):
            assert isinstance(dataset, Sized)
            self.dataset_len = len(dataset)
        else:
            self.dataset_len = len(list(dataset))
`

**Comment by rubick1896** [comment] 2020-08-25 03:11
@lostella Even if I could provide the the __len__ function in the Dataset object, the data loading process still doesn't work properly. The process seems to stuck at some point(most likely to be _sequential_sample_generator function). Try the code below.

dataset = get_dataset("m4_hourly", regenerate=True)

class MyDataset():
    def __init__(
        self,
        data_iter: Iterable[DataEntry],
        freq: str,
        one_dim_target: bool = True,
    ) -> None:
        #self.process = ProcessDataEntry(freq, one_dim_target)
        self.list_data = (x for x in data_iter)  # dataset always cached

    def __iter__(self) -> Iterator[DataEntry]:
        source_name = "list_data"
        # Basic idea is to split the dataset into roughly equally sized segments
        # with lower and upper bound, where each worker is assigned one segment
        bounds = util.get_bounds_for_mp_data_loading(len(self))
        for row_number, data in enumerate(self.list_data):
            if not bounds.lower <= row_number < bounds.upper:
                continue

            #data["source"] = SourceContext(source=source_name, row=row_number)
            yield data

    def __len__(self):
        #return len(self.list_data)
        return 414
        
b = MyDataset(dataset.train, freq=dataset.metadata.freq)

c = 0
a = _sequential_sample_generator(b, estimator.create_transformation(), is_train=True, cyclic=True)

while True:
    start_time = time.time()
    for item in a:
        c += 1
        if c % 10000 == 0:
            print(c, time.time() - start_time)

If I just replace the list_data field with a normal list it works properly.

**Comment by rubick1896** [comment] 2020-09-09 09:45
@lostella Could you give some feedback on this issue? Is this a bug?

**Comment by lostella** [comment] 2020-09-09 12:22
@rubick1896 I think the call to `list(dataset)` is not an issue anymore, since #986 was merged: I will check whether this can be safely back-ported to the `v0.5.x` branch, in which case it will be part of the next `v0.5.3` release.

About your custom dataset issue, there's ongoing work about simplifying the data loader structure, see #898. This will be hopefully merged soon, and be part of `v0.6.x`. Do you have a way to try whether the branch from #898 works for your case?

**Comment by rubick1896** [comment] 2020-09-10 02:51
Thanks for the response. I  like your simplified version of dataloader. My problem is not solved. Here is the code that is causing the problem
``` python
class CyclicIterable(Iterable):
    def __init__(self, base_iterable: Iterable) -> None:
        self.base_iterable = base_iterable

    def __iter__(self):
        while True:
            yield from self.base_iterable
```
If this Iterable is not a list but a generator object, it stuck in the loop without doing anything. Frankly, 
`
while True:
    yield from somthing
`
is confusing. Just by looking at the code , I don't know what to expect from it. Here is a simple example
``` python
l = [1,2,3,4,5]
gen = (x for x in l)

s_gen = CyclicIterable(l)

c = 0
for item in s_gen:
    c += 1
    if c % 10000 == 0:
        print(c, time.time() - start_time)
 ```

Maybe use itertools.cycle could be a simple fix. like
``` python
import itertools
class CyclicIterable(Iterable):
    def __init__(self, base_iterable: Iterable) -> None:
        self.base_iterable = base_iterable

    def __iter__(self):
        yield from itertools.cycle(self.base_iterable)
```

**Comment by lostella** [comment] 2020-09-10 08:30
@rubick1896 what to expect from `CyclicIterable` is the following (adapted from your snippet):

```python
from typing import Iterable

class CyclicIterable(Iterable):
    def __init__(self, base_iterable: Iterable) -> None:
        self.base_iterable = base_iterable

    def __iter__(self):
        while True:
            yield from self.base_iterable

l = [1,2,3,4,5]
cl = CyclicIterable(l)

from itertools import islice

for item in islice(cl, 11):
    print(item)
```

which prints:

```python
1
2
3
4
5
1
2
3
4
5
1
```

The main reason not to use `itertools.cycle` is that it allocates, see description here https://docs.python.org/3.7/library/itertools.html#itertools.cycle

**Comment by rubick1896** [comment] 2020-09-10 10:11
@lostella 
I guess I wasn't clear on the example. `l` is a list, if you just substitute that with `gen`,  you will see the behavior is not the same from the list. It prints [1,2,3,4,5] and stuck in the infinite loop. If you use cycle it gives the correct output.

**Comment by lostella** [comment] 2020-09-10 13:37
@rubick1896 ok, now I get what you mean, thanks for clarifying.

So the issue is that the generator expression gives you an iterator which is exhausted once you have iterated it. The (maybe too subtle) assumption in `CyclicIterable` is that the object that you wrap can be iterated over multiple times and always yield the same elements: essentially, it should be a stateless container, as opposed to a stateful iterator. The `FileDataset` class from GluonTS has this property.

I guess that the same thing applies to `_sequential_sample_generator` with `cyclic=True` further above.

**Comment by rubick1896** [comment] 2020-09-11 04:03
@lostella 
How to make an object stateless container without caching it in memory? Here is sort of my situation
```python
class SmallData():
    def __init__(self):
        self.dataset = get_dataset("m4_hourly").train

    def __iter__(self):
        for item in self.dataset:
            yield item

class LargeData():
    def __init__(self):
        self.dataset = [SmallData(), SmallData(), SmallData()]

    def __iter__(self):
        for item in self.dataset:
            for data_entry in item:
                yield data_entry

```
When I get an instance of LargeData it will load all data(3 times SmallData) in memory, which I cannot afford. What I did was
```python
def load_func():
    for item in get_dataset("m4_hourly").train:
        yield item

class SmallData():
    def __init__(self):
        self.dataset = load_func()#get_dataset("m4_hourly").train

    def __iter__(self):
        for item in self.dataset:
            yield item

class LargeData():
    def __init__(self):
        self.dataset = [SmallData(), SmallData(), SmallData()]

    def __iter__(self):
        for item in self.dataset:
            for data_entry in item:
                yield data_entry
```
But, this has the issue of the exhausting iterator. Really need some help here, thanks in advance.

**Comment by lostella** [comment] 2020-09-11 07:06
> When I get an instance of LargeData it will load all data(3 times SmallData) in memory, which I cannot afford.

I don't think that's the case: `LargeData` will store three objects of type `SmallData` in memory, each of which has a `dataset` attribute of type `FileDataset`, which will not be loaded from disk as a whole, but rather iterated line by line.

In fact, I think your first example should work for your use case, shouldn't it?

**Comment by rubick1896** [comment] 2020-09-12 03:51
Well, that was meant to be an example of my own loading function, when called will load all data into memory. If I could use `FileDataset`, it wouldn't be an issue in the first place. I actually get it to train by doing something like this
```python
def load_func():
    for item in get_dataset("m4_hourly").train:
        yield item

class SmallData():
    def __init__(self):
        self.dataset = load_func()#get_dataset("m4_hourly").train

    def __iter__(self):
        return self

    def __next__(self):
        try:
            return next(self.dataset)
        except:
            self.dataset = load_func()
            raise StopIteration

```
But this only works when num_workers is set to 0. When `num_workers` is set to be greater than 0, it gives the following report
```
  0%|          | 0/200 [00:00<?, ?it/s]/home/wenrui29/.opt/anaconda/envs/gluon/lib/python3.7/site-packages/ipykernel_launcher.py:35: RuntimeWarning: invalid value encountered in true_divide
Process Process-2:
Traceback (most recent call last):
  File "/home/wenrui29/.opt/anaconda/envs/gluon/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/wenrui29/.opt/anaconda/envs/gluon/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wenrui29/src/gluon-ts/src/gluonts/dataset/loader.py", line 151, in worker_fn
    batch = batchify_fn(batch_list)
  File "/home/wenrui29/src/gluon-ts/src/gluonts/mx/batchify.py", line 96, in batchify
    for key in data[0].keys()
  File "/home/wenrui29/src/gluon-ts/src/gluonts/mx/batchify.py", line 96, in <dictcomp>
    for key in data[0].keys()
  File "/home/wenrui29/src/gluon-ts/src/gluonts/mx/batchify.py", line 77, in stack
    data = mx.nd.array(data, dtype=dtype, ctx=ctx)
  File "/home/wenrui29/.opt/anaconda/envs/gluon/lib/python3.7/site-packages/mxnet/ndarray/utils.py", line 146, in array
    return _array(source_array, ctx=ctx, dtype=dtype)
  File "/home/wenrui29/.opt/anaconda/envs/gluon/lib/python3.7/site-packages/mxnet/ndarray/ndarray.py", line 3371, in array
    arr = empty(source_array.shape, ctx, dtype)
  File "/home/wenrui29/.opt/anaconda/envs/gluon/lib/python3.7/site-packages/mxnet/ndarray/ndarray.py", line 4822, in empty
    return NDArray(handle=_new_alloc_handle(shape, ctx, False, dtype))
  File "/home/wenrui29/.opt/anaconda/envs/gluon/lib/python3.7/site-packages/mxnet/ndarray/ndarray.py", line 186, in _new_alloc_handle
    ctypes.byref(hdl)))
  File "/home/wenrui29/.opt/anaconda/envs/gluon/lib/python3.7/site-packages/mxnet/base.py", line 246, in check_call
    raise get_last_ffi_error()
mxnet.base.MXNetError: Traceback (most recent call last):
  File "src/engine/./../common/cuda_utils.h", line 379
CUDA: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading: initialization error
  0%|          | 0/200 [02:00<?, ?it/s]
learning rate from ``lr_scheduler`` has been overwritten by ``learning_rate`` in optimizer.
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-4-0faffcf74942> in <module>
----> 1 predictor = estimator.train(train_ds, num_workers=1)

~/src/gluon-ts/src/gluonts/model/estimator.py in train(self, training_data, validation_data, num_workers, num_prefetch, shuffle_buffer_length, **kwargs)
    274             num_prefetch,
    275             shuffle_buffer_length,
--> 276             **kwargs,
    277         ).predictor

~/src/gluon-ts/src/gluonts/model/estimator.py in train_model(self, training_data, validation_data, num_workers, num_prefetch, shuffle_buffer_length, **kwargs)
    247             input_names=get_hybrid_forward_input_names(trained_net),
    248             train_iter=training_data_loader,
--> 249             validation_iter=validation_data_loader,
    250         )
    251 

~/src/gluon-ts/src/gluonts/mx/trainer/_base.py in __call__(self, net, input_names, train_iter, validation_iter)
    326                     )
    327 
--> 328                     epoch_loss = loop(epoch_no, train_iter)
    329                     if is_validation_available:
    330                         epoch_loss = loop(

~/src/gluon-ts/src/gluonts/mx/trainer/_base.py in loop(epoch_no, batch_iter, is_training)
    305                         epoch_no,
    306                         ("" if is_training else "validation_") + "epoch_loss",
--> 307                         lv,
    308                     )
    309 

UnboundLocalError: local variable 'lv' referenced before assignment
```

**Closed** 2020-09-21 09:09 UTC
Labels: question
